server:
  port: 8084

spring:
  application:
    name: NOTIFICATION-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/heathcare
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: notification_service
        hbm2ddl.create_namespaces: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: your_email@gmail.com
    password: your_app_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
