server:
  port: 8082

spring:
  application:
    name: ORDER-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/heathcare
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: order_service
        hbm2ddl.create_namespaces: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

prescription:
  upload:
    dir: uploads/prescriptions
